// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOoILl2HiYlzNQiE65AvP524tBw8EWmQ',
    appId: '1:796583590652:web:ac2897ab6c756eba243579',
    messagingSenderId: '796583590652',
    projectId: 'km-rentals',
    authDomain: 'km-rentals.firebaseapp.com',
    storageBucket: 'km-rentals.firebasestorage.app',
    measurementId: 'G-QZNMYZK5C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGr2yjNHa1Z2mRsYR1bEpd1vAkTydlX0',
    appId: '1:796583590652:android:6b8f80e227d72c78243579',
    messagingSenderId: '796583590652',
    projectId: 'km-rentals',
    storageBucket: 'km-rentals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmd8AGw3f6cnDvWQo979EMYX0n1SZAsXo',
    appId: '1:796583590652:ios:1e2eac7be3200e79243579',
    messagingSenderId: '796583590652',
    projectId: 'km-rentals',
    storageBucket: 'km-rentals.firebasestorage.app',
    iosClientId: '796583590652-iqa5jd026qbh9tivs92uf8jvbmskhtd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentApp',
  );

}